.segment "ZEROPAGE": zeropage

joy_current:        .res 2
joy_previous:       .res 2
joy_pressed:        .res 2
text_cursor:        .res 2
text_ptr:           .res 2
text_palette:       .res 2
menu_index:         .res 2
ui_index:           .res 2
ui_line:            .res 2
current_test:       .res 2
current_desc:       .res 2
current_flags:      .res 2
timeout_count:      .res 2
repeat_count:       .res 2
test_result:        .res 2
last_expected:      .res 2
last_actual:        .res 2
last_address:       .res 2
pass_count:         .res 2
fail_count:         .res 2
timeout_total:      .res 2
first_failure:      .res 2
clear_first:        .res 2
clear_last:         .res 2
clear_col:          .res 2
clear_row:          .res 2
clear_tile_addr:    .res 2
visual_source:      .res 2
temp_word:          .res 2
