#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

VISIBLE_SCANLINES = 224

# Fixed-color intensities are 5-bit values. The effect is intentionally dark so
# white diagnostic text remains the dominant visual element.
THEMES = {
    "Normal": ((1, 4, 9), (0, 1, 3)),
    "Pass": ((1, 8, 4), (0, 2, 1)),
    "Fail": ((9, 2, 3), (3, 0, 1)),
    "Timeout": ((10, 6, 1), (3, 2, 0)),
}

COMPONENTS = (
    ("Red", 0, 0x20),
    ("Green", 1, 0x40),
    ("Blue", 2, 0x80),
)


def interpolate(start: int, end: int, index: int) -> int:
    if VISIBLE_SCANLINES <= 1:
        return start
    numerator = start * (VISIBLE_SCANLINES - 1 - index) + end * index
    return (numerator + (VISIBLE_SCANLINES - 1) // 2) // (VISIBLE_SCANLINES - 1)


def component_values(start_rgb: tuple[int, int, int], end_rgb: tuple[int, int, int], component: int) -> list[int]:
    return [interpolate(start_rgb[component], end_rgb[component], line) for line in range(VISIBLE_SCANLINES)]


def build_table(values: list[int], component_flag: int) -> bytes:
    if len(values) != VISIBLE_SCANLINES:
        raise ValueError(f"HDMA gradient must contain {VISIBLE_SCANLINES} scanlines")

    out = bytearray()
    for value in values:
        if not 0 <= value <= 31:
            raise ValueError(f"fixed-color component {value} is outside 0..31")
        # One direct HDMA transfer on each visible scanline. This is larger than
        # a compressed table, but deliberately simple and deterministic.
        out += bytes((1, component_flag | value))
    out.append(0)
    return bytes(out)


def build_all_tables() -> dict[str, bytes]:
    tables: dict[str, bytes] = {}
    for theme, (start_rgb, end_rgb) in THEMES.items():
        for component_name, component, flag in COMPONENTS:
            label = f"Bg{theme}{component_name}"
            tables[label] = build_table(component_values(start_rgb, end_rgb, component), flag)
    return tables


def format_table(label: str, data: bytes) -> list[str]:
    lines = [f"{label}:"]
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        lines.append("    .byte " + ",".join(f"${value:02X}" for value in chunk))
    lines.append("")
    return lines


def build_include() -> str:
    lines = [
        "; Generated by tools/gen_background.py. Do not edit by hand.",
        "; Each table is a direct HDMA stream for one COLDATA component.",
        "",
    ]
    for label, data in build_all_tables().items():
        lines.extend(format_table(label, data))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    text = build_include()
    args.output.write_text(text)
    print(f"Wrote {args.output} ({len(build_all_tables())} HDMA tables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
